### ISSUE TITLE
different camera

### ISSUE THREAD

**Issue by arafatsh** [appliedAI-Initiative/orb_slam_2_ros#6]
sorry for this question but i am havin a problem with something.
I want to use the zed camera instead of the cameras you mentioned so what should i change?
your config files are in .yaml format and mine is in .conf !
And from inside they are different >
attached below is my file..

..........................................................................................................

﻿[LEFT_CAM_2K]
fx = 1398.9
fy = 1398.9
cx = 1160.34
cy = 646.38
k1 = -0.177442
k2 = 0.0297199
p1 = 0
p2 = 0

[RIGHT_CAM_2K]
fx = 1400.52
fy = 1400.52
cx = 1133.7
cy = 622.971
k1 = -0.175378
k2 = 0.0290574
p1 = 0
p2 = 0

[LEFT_CAM_FHD]
fx = 1398.9
fy = 1398.9
cx = 1016.34
cy = 565.38
k1 = -0.177442
k2 = 0.0297199
p1 = 0
p2 = 0

[RIGHT_CAM_FHD]
fx = 1400.52
fy = 1400.52
cx = 989.702
cy = 541.971
k1 = -0.175378
k2 = 0.0290574
p1 = 0
p2 = 0

[LEFT_CAM_HD]
fx = 699.449
fy = 699.449
cx = 666.67
cy = 371.19
k1 = -0.177442
k2 = 0.0297199
p1 = 0
p2 = 0

[RIGHT_CAM_HD]
fx = 700.259
fy = 700.259
cx = 653.351
cy = 359.486
k1 = -0.175378
k2 = 0.0290574
p1 = 0
p2 = 0

[LEFT_CAM_VGA]
fx = 349.724
fy = 349.724
cx = 348.835
cy = 193.095
k1 = -0.177442
k2 = 0.0297199
p1 = 0
p2 = 0

[RIGHT_CAM_VGA]
fx = 350.129
fy = 350.129
cx = 342.175
cy = 187.243
k1 = -0.175378
k2 = 0.0290574
p1 = 0
p2 = 0

[STEREO]
Baseline = 120
CV_2K = 0.0136559
CV_FHD = 0.0136559
CV_HD = 0.0136559
CV_VGA = 0.0136559
RX_2K = -0.00678823
RX_FHD = -0.00678823
RX_HD = -0.00678823
RX_VGA = -0.00678823
RZ_2K = -0.0000106558
RZ_FHD = -0.0000106558
RZ_HD = -0.0000106558
RZ_VGA = -0.0000106558

**Comment by lennarthaller** [comment]
Familiarize yourself with the parameters for example by reading [this](https://docs.opencv.org/3.1.0/dc/dbb/tutorial_py_calibration.html).
Take the RealSenseR200Stereo.yaml file as a template and replace the relevant parameters (the intrinsic calibration and the baseline. Not sure if you need to rectify the images from the ZED or if they come pre-rectified - you need to check this.)
Since you already have your parameters you don't need to do this, but just for the sake of completeness and if other people stumble upon this issue: use for example this [ROS node](http://wiki.ros.org/camera_calibration) to get the calibration parameters.

Hope that helps!
